### ISSUE TITLE
Can't find deluge state directory

### ISSUE THREAD

**Issue by protagonyst** [rumanzo/deluge2qbt#5]
If I just run the application, I get the following message :

> Can't find deluge folder

I checked the correct paths.

Source torrent client is uTorrent v2.2.1 and its folder is _C:\Users\Sebastien\AppData\Roaming\uTorrent_. It contains all my .torrent files and _resume.dat_.

Destination torrent client is qBitTorrent 4.3.1 and its folder is _C:\Users\Sebastien\AppData\Local\qBittorrent\BT_backup_.

I used the following command line :

`deluge2qbt_v1.3_amd64.exe -s C:\Users\Sebastien\AppData\Roaming\uTorrent -d C:\Users\Sebastien\AppData\Local\qBittorrent\BT_backup\
`

I get the following message :

> Can't find deluge state directory

**Desktop (please complete the following information):**
 - OS: Windows 8.1

**Comment by rumanzo** [comment]
You need use bt2qbt to import your torrents from utorrent to qBittorrent. deluge2qbt is for migrating from deluge torrent client
See https://github.com/rumanzo/bt2qbt/

**Comment by cgiAlexis** [comment]
rumanzo doesn't that mean you want to edit the first line in the readme.md for this project to correcty read "From **Deluge** to qBittorrent" rather than the current state;

> # deluge2qbt
> deluge2qbt is cli tool for export from **uTorrent\Bittorrent** into qBittorrent (convert)

**Comment by rumanzo** [comment]
https://github.com/rumanzo/deluge2qbt/releases/tag/v1.4 should fix all issues
