### ISSUE TITLE
Says it works, then doesn't actually work.

### ISSUE THREAD

**Issue by wyvernx23** [rumanzo/deluge2qbt#6]
**Describe the bug**
Does not copy any of my files overs from deluge

**To Reproduce**
1. Go to the .exe
2. Double click the .exe
3. Watch it reproduce the files successfully on the command prompt
4. Open and see no changes to qbittorrent

**Expected behavior**
100% transfer that actually transfers

**Desktop (please complete the following information):**
Windows 10 64bit

**Additional context**
The example usage guide is confusing and does not appear written for people who do not code such as myself.

**Comment by wyvernx23** [comment]
bump

**Comment by rumanzo** [comment]
https://github.com/rumanzo/deluge2qbt/releases/tag/v1.4 should fix all issues
