### ISSUE TITLE
"Can't decode deluge fastresume file"

### ISSUE THREAD

**Issue by freonpsandoz** [rumanzo/deluge2qbt#8]
I used the command "deluge2qbt_v1.3_amd64.exe -s=%APPDATA%\uTorrent"
Is this correct for migrating a uTorrent configuration?

I'm getting the error "Can't decode deluge fastresume file." 

I expected files to be placed in "%LOCALAPPDATA%\qBittorrent\BT_backup" but there are none.

 - OS: Windows 10 Pro 2004 Build 19041.1083

I don't seem to be able to attach the uTorrent resume.dat file, but I can email it (it's about 12MB.)

**Comment by rumanzo** [comment]
Hello! You got wrong distributive. If you would migrate from utorrent, you should use https://github.com/rumanzo/bt2qbt

**Comment by freonpsandoz** [comment]
Oops, sorry! bt2qbt_v1.11_amd64.exe seems to be working fine.
