### ISSUE TITLE
Can't convert with can't create file fastresume

### ISSUE THREAD

**Issue by ricain59** [rumanzo/deluge2qbt#9]
Hi,

debian11 deluge 2.0.3 to qbittorrent 4.2.5

I try used the script but give me this errors:
2021/11/18 21:35:41 Can't create qBittorrent fastresume file /root/.local/share/data/qBittorrent/BT_backup/68e2713bde8f16dba0c7862a5c52b1de28cf926e.fastresume

If i start again qbittorrent not have torrents. 
Any solution?

Thank you for your script.

**Comment by rumanzo** [comment]
Hello! Do you really want use qBittorent as root user?

**Comment by ricain59** [comment]
Hi, 
I use version 1.2 and working.
But you have reason, i got changed user ;)

**Comment by rumanzo** [comment]
Is the problem resolved?

**Comment by ricain59** [comment]
Yes,

I have used version 1.2 with the new user. With user root version 1.2 works fine.

Thank you for your work.

**Comment by firecat53** [comment]
I also had to build version 1.2 or I received the same errors as the OP.  I was running the script as a non-root user.

    $ ./deluge2qbt -c /qbt/qBittorrent/qBittorrent.conf -d /qbt/qBittorrent/BT_backup/ -s /deluge/

**Comment by kdurov** [comment]
Same here. Only version 1.2 works ( deluged 2.05 to qBittorrent )

**Comment by rekk2** [comment]
1.2 works, 1.3 does not

**Comment by rumanzo** [comment]
> I also had to build version 1.2 or I received the same errors as the OP. I was running the script as a non-root user.
> 
> ```
> $ ./deluge2qbt -c /qbt/qBittorrent/qBittorrent.conf -d /qbt/qBittorrent/BT_backup/ -s /deluge/
> ```

In your case I guess that /qbt is non-user directory without write permission. You can check it manually

**Comment by rumanzo** [comment]
> Same here. Only version 1.2 works ( deluged 2.05 to qBittorrent )



> 1.2 works, 1.3 does not

What kind of errors you get with 1.3?

**Comment by rekk2** [comment]
it says it couldn't create the fastresume file, but in reality it made 0kb
fastresume files.  using windows

**Comment by slydog3333** [comment]
Same thing happened to me with 1.3. Going from deluge 2.1.1 to qbittorent 4.4.5 in Windows 10.

Version 1.2 works great though, thank you for you work.

**Comment by rumanzo** [comment]
https://github.com/rumanzo/deluge2qbt/releases/tag/v1.4 should fix all issues
